services:
  weather-postgres:
    image: postgres
    container_name: weather-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - weather_postgres_data:/var/lib/postgresql/data

volumes:
  weather_postgres_data: